import { NextRequest, NextResponse } from "next/server";
import { languageName } from "@/lib/game/languages";
import { resolveBanterPack } from "@/lib/server/anthropic";
import { createSession, setSessionBanter } from "@/lib/server/session-store";
import type { CreateSessionInput } from "@/lib/session/types";
import type { ErrorResponse } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json().catch(() => ({}))) as CreateSessionInput;
    const session = createSession(body);
    // en/it resolve instantly (static); other languages are generated by Claude
    // once and cached, so the host gets a fully localized narrator on entry.
    const banter = await resolveBanterPack(session.narratorLang, languageName(session.narratorLang));
    setSessionBanter(session.code, banter);
    return NextResponse.json({ session: { ...session, banter } });
  } catch {
    return NextResponse.json<ErrorResponse>(
      { error: "Could not create a session.", code: "session_create_failed" },
      { status: 500 },
    );
  }
}
