import type { SessionRound } from "@/lib/session/types";

// A localized set of host-narrator lines. Templates use {placeholder} tokens
// filled in at runtime (player name, lyric, room code, …). The static IT/EN
// packs below ship in the bundle; packs for other languages are generated by
// Claude at session creation (see lib/server/anthropic.ts) — the interpolation
// always stays in code, so the LLM never touches player names or solutions.
export interface BanterPack {
  /** 3 roast templates — placeholders {name} {guess} {solution}. */
  roasts: string[];
  /** 3 round-intro templates — placeholder {title}. */
  intros: string[];
  /** Welcome line with players present — {code} {players}. */
  welcomeWith: string;
  /** Welcome line for an empty room — {code}. */
  welcomeEmpty: string;
  /** Closing line with a winner — {leader}. */
  finalWith: string;
  /** Closing line with no ranked leader. */
  finalEmpty: string;
  /** Reveal: who leads — {leader}. */
  leaderLine: string;
  /** Reveal: no ranked leader yet. */
  scoresLocked: string;
  /** Reveal: announce the answer — {solution}. */
  answerLine: string;
  /** Reveal: answers received, no single solution to read out. */
  answersIn: string;
  /** Reveal prefix — {index}. */
  roundLabel: string;
}

const MAX_LEN = 400; // ElevenLabs truncates at 420 chars; stay under with room for the leader line.

// Lines are deliberately terse — the host says little and gets out of the way.
const EN_PACK: BanterPack = {
  roasts: [
    "{name} went «{guess}». It was «{solution}».",
    "«{guess}»? Nope — «{solution}».",
    "{name} missed it. «{solution}».",
  ],
  intros: ["{title}!", "Next: {title}.", "{title} — go!"],
  welcomeWith: "Room {code}. Let's play!",
  welcomeEmpty: "Room {code}. Grab your phones.",
  finalWith: "{leader} wins!",
  finalEmpty: "That's a wrap!",
  leaderLine: "{leader} leads.",
  scoresLocked: "Scores locked.",
  answerLine: "«{solution}».",
  answersIn: "Answers in.",
  roundLabel: "Round {index}.",
};

const IT_PACK: BanterPack = {
  roasts: [
    "{name} ha detto «{guess}». Era «{solution}».",
    "«{guess}»? No — «{solution}».",
    "{name} l'ha sbagliata. «{solution}».",
  ],
  intros: ["{title}!", "Ora: {title}.", "{title} — via!"],
  welcomeWith: "Stanza {code}. Si gioca!",
  welcomeEmpty: "Stanza {code}. Telefoni alla mano.",
  finalWith: "{leader} vince!",
  finalEmpty: "È finita!",
  leaderLine: "{leader} comanda.",
  scoresLocked: "Punteggi bloccati.",
  answerLine: "«{solution}».",
  answersIn: "Risposte arrivate.",
  roundLabel: "Round {index}.",
};

// Languages we ship hand-written packs for (zero latency, deterministic). Any
// other supported language is filled in by Claude at session creation.
const STATIC_BANTER_PACKS: Record<string, BanterPack> = { en: EN_PACK, it: IT_PACK };

export const DEFAULT_BANTER_PACK: BanterPack = EN_PACK;

export function staticBanterPack(code: string): BanterPack | undefined {
  return STATIC_BANTER_PACKS[code];
}

function fill(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => vars[key] ?? `{${key}}`);
}

/**
 * Build a roast line for the reveal: picks one wrong answer deterministically and
 * mocks the player by name. Returns null when there is no solution or no wrong
 * answer to roast — the caller then falls back to the neutral announcement.
 */
export function buildRoastLine(
  round: Pick<SessionRound, "index" | "solution" | "answers">,
  pack: BanterPack,
): string | null {
  const solution = round.solution?.trim();
  if (!solution) return null;

  const wrong = round.answers.filter((answer) => !answer.correct && answer.guess.trim());
  if (wrong.length === 0) return null;

  const pick = wrong[Math.abs(round.index * 37 + 11) % wrong.length];
  const template = pack.roasts[Math.abs(round.index * 13) % pack.roasts.length];
  const line = fill(template, { name: pick.playerName, guess: pick.guess.trim(), solution });
  return line.length > MAX_LEN ? `${line.slice(0, MAX_LEN - 1)}…` : line;
}

export function roundIntroLine(title: string, index: number, pack: BanterPack): string {
  return fill(pack.intros[Math.abs(index) % pack.intros.length], { title });
}

export function welcomeLine(code: string, players: number, pack: BanterPack): string {
  return players > 0
    ? fill(pack.welcomeWith, { code, players: String(players) })
    : fill(pack.welcomeEmpty, { code });
}

export function finalLine(leader: string | undefined, pack: BanterPack): string {
  return leader ? fill(pack.finalWith, { leader }) : pack.finalEmpty;
}

// Reveal helpers — these replace the inline IT/EN ternaries that used to live in
// HostRoom, so every supported language localizes the reveal too.
export function revealLeaderLine(leader: string | undefined, pack: BanterPack): string {
  return leader ? fill(pack.leaderLine, { leader }) : pack.scoresLocked;
}

export function revealAnswerLine(solution: string | undefined, pack: BanterPack): string {
  return solution ? fill(pack.answerLine, { solution }) : pack.answersIn;
}

export function roundLabel(index: number, pack: BanterPack): string {
  return fill(pack.roundLabel, { index: String(index) });
}
